version: 2

sphinx:
  configuration: docs/source/conf.py 
  builder: html
#  fail_on_warning: true
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
python:
  version: 3.8
  # Install our python package before building the docs
#  install:
#    - method: pip
#      path: .

#formats:
#  - pdf
