[project]
name = 'seastar'
description = 'seastar package'
version = '1.0'
dependencies = ['numpy', 'pandas', ''scipy', 'xarray']

[build-system]
build-backend = 'flit_core.buildapi'
requires = ['flit_core >=3.2,<4']
