[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]


name = "seastar_project"
description = "titanic_ml example package"
version = "0.1.0"
dependencies = ["numpy", "xarray"]
