[project]
name = 'master_processor'
description = 'seastar package'
version = '1.0'
dependencies = ['numpy', 'scipy', 'xarray']


[build-system]
build-backend = 'flit_core.buildapi'
requires = ['flit_core >=3.2,<4']
