name: seastar
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.5.1
  - netcdf4=1.5.7
  - notebook
  - numpy=1.21.5
  - packaging
  - pandas=1.3.5
  - pip
  - python=3.7
  - spyder
  - xarray=0.20.1
