name: seastar
channels:
#  - defaults
  - conda-forge
dependencies:
  - python
  - matplotlib
  - netcdf4
  - notebook
  - numpy
  - scipy
  - packaging
  - pip
  - sphinx
  - sphinx_rtd_theme
  - xarray
  - cartopy
  - utm
  - pytest
