name: seastar
channels:
#  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.5.1
  - netcdf4=1.5.7
  - notebook=6.4.11
  - numpy=1.22.4
  - scipy=1.7.3
  - packaging
  - pip
  - python=3.8
  - spyder=3.3.6
  - sphinx=4.4.0
  - sphinx_rtd_theme=1.0.0
  - xarray=2022.11.0
  - cartopy=0.18.0
  - utm=0.7.0