name: seastar
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.5.1
  - netcdf4=1.5.7
  - notebook=6.4.11
  - numpy=1.21.5
  - scipy=1.7.3
  - packaging
  - pandas=1.3.5
  - pip=21.2.4
  - python=3.7
  - spyder=3.3.6
  - xarray=0.20.1
